#include "bitmanip.h"
#include "board.h"
#include "common.h"
#include "pawns.h"

#include <gtest/gtest.h>

TEST(PawnsTest, DoubledPawns) {
  Board board(Variant::ANTICHESS, "8/p3p3/pP1p4/8/1PPp4/8/8/8 w - -");
  EXPECT_EQ(1, PopCount(pawns::DoubledPawns(board, Side::WHITE)));
  EXPECT_EQ(2, PopCount(pawns::DoubledPawns(board, Side::BLACK)));
}

TEST(PawnsTest, PassedPawns) {
  Board board(Variant::STANDARD, "6n1/3q4/4p1pp/2Pp4/1P3P2/8/2Q5/4R3 w - -");
  EXPECT_EQ(bitmanip::FromLayout(R"""(
    ........
    ........
    ........
    ..1.....
    .1......
    ........
    ........
    ........
  )"""),
            pawns::PassedPawns(board, Side::WHITE));
  EXPECT_EQ(bitmanip::FromLayout(R"""(
    ........
    ........
    .......1
    ...1....
    ........
    ........
    ........
    ........
  )"""),
            pawns::PassedPawns(board, Side::BLACK));
}
